name: Build and Publish Image to Docker Hub

on:
  push:
    branches:
      - main
      paths:
        - 'api/Dockerfile'
        - 'front-end-nextjs/Dockerfile'  # This triggers when change is made in the dockerfile

jobs:
  publish_image:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4  # Use the latest version of actions/checkout
        
      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build ./api/ -t alpaccino138/devops-qr-code-api-repo:latest  # Build the image and tag it
          docker build ./front-end-nextjs/ -t alpaccino138/devops-qr-code-frontend-repo:latest  # Build the image and tag it

      # Push the Docker image to Docker Hub
      - name: Push image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}  # Use secrets for username and token
          docker push alpaccino138/devops-qr-code-api-repo:latest  # Push the built image to Docker Hub
          docker push alpaccino138/devops-qr-code-frontend-repo:latest  # Push the built image to Docker Hub
